const strassennamen = [
  "Achteresch",
  "Achterkehrstraße",
  "Achterwälde",
  "Adeliger Hof",
  "Adlerstraße",
  "Adolfstraße",
  "Ahornweg",
  "Ahrensstraße",
  "Akazienweg",
  "Albert-Schweitzer-Straße",
  "Albrechtstraße",
  "Alexanderstraße",
  "Alpenrosenstraße",
  "Alt-Mundersum",
  "Altbrockhausen",
  "Alte Dorfstraße",
  "Alte Gärtnerei",
  "Alte Haselünner Straße",
  "Alte Josefstraße",
  "Alte Rheiner Straße",
  "Altenlingen-Dorf",
  "Altenlingener Sand",
  "Altenlingener Weg",
  "Alter Hafenspeicher",
  "Alter Jagdweg",
  "Alter Kleinbahndamm",
  "Alter Pferdemarkt",
  "Alter Sportplatz",
  "Altes Sägewerk",
  "Am Alten Flugplatz",
  "Am Alten Friedhof",
  "Am Alten Hafen",
  "Am Ameisenhügel",
  "Am Bahndamm",
  "Am Berg",
  "Am Berggarten",
  "Am Biener Esch",
  "Am Biener Sand",
  "Am Biener See",
  "Am Birkenhain",
  "Am Bloomholt",
  "Am Botterkamp",
  "Am Brink",
  "Am Bronzefeld",
  "Am Brunnenpark",
  "Am Buchenhain",
  "Am Buchenwald",
  "Am Bunker",
  "Am Böckel",
  "Am Dachsbau",
  "Am Dallgraben",
  "Am Damm",
  "Am Darmer Bahndamm",
  "Am Darmer Sportzentrum",
  "Am Darmer Wasserwerk",
  "Am Dieksee",
  "Am Dreieck",
  "Am Dreispitz",
  "Am Durchstich",
  "Am Düker",
  "Am Falkenhorst",
  "Am Forst",
  "Am Forstpfad",
  "Am Fährdamm",
  "Am Galgenesch",
  "Am Gasthausdamm",
  "Am Gemeinschaftshaus",
  "Am Grabenkamp",
  "Am Grünen Revier",
  "Am Hasenbrink",
  "Am Heidkamp",
  "Am Heimathaus",
  "Am Hilgenberg",
  "Am Hundesand",
  "Am Kanal",
  "Am Kanaldamm",
  "Am Kaninchenberg",
  "Am Kindergarten",
  "Am Kirchblick",
  "Am Kohschultenhof",
  "Am Kreuzbach",
  "Am Kurpark",
  "Am Laxtener Esch",
  "Am Markengrund",
  "Am Markt",
  "Am Mühlenbach",
  "Am Mühlenberg",
  "Am Mühlenstein",
  "Am Neuen Friedhof",
  "Am Papenbruch",
  "Am Pulverturm",
  "Am Pumpenkolk",
  "Am Reinelhof",
  "Am Robbenpohl",
  "Am Sandhügel",
  "Am Schallenbach",
  "Am Seitenkanal",
  "Am Sender",
  "Am Sonnenhang",
  "Am Speichersee",
  "Am Sperrtor",
  "Am Sportplatz",
  "Am Storchengrund",
  "Am Strootbach",
  "Am Strubbenberg",
  "Am Tankfeld",
  "Am Telgenkamp",
  "Am Treffpunkt",
  "Am Vennbach",
  "Am Wacholderhain",
  "Am Wachtelring",
  "Am Waldessaum",
  "Am Waldfriedhof",
  "Am Waldhügel",
  "Am Waldstadion",
  "Am Wall-Nord",
  "Am Wall-Ost",
  "Am Wall-Süd",
  "Am Wallgraben",
  "Am Walzkamp",
  "Am Wasserfall",
  "Am Wiesengrund",
  "Am Wildwechsel",
  "Am Wollenkamp",
  "Am Wulwer Esch",
  "Am Ölwerk",
  "Am Övernhoff",
  "Amselweg",
  "An Becker`s Hof",
  "An den Höfen",
  "An den Städt. Tannen",
  "An der Gräfte",
  "An der Kapelle",
  "An der Kokenmühle",
  "An der Marienschule",
  "An der Schleuse",
  "An der Schonung",
  "An der Seilerei",
  "An der Wilhelmshöhe",
  "Anemonenstraße",
  "Anglerstraße",
  "Ankestraße",
  "Anna-Brauer-Straße",
  "Antoniusstraße",
  "Apollostraße",
  "Asternweg",
  "Auf dem Bache",
  "Auf der Haar",
  "Auf der Loos",
  "Auguststraße",
  "Auricher Straße",
  "Azaleenstraße",
  "Baccumer Berg",
  "Baccumer Straße",
  "Bacheimstraße",
  "Bachstraße",
  "Bahnstraße",
  "Baltrumer Straße",
  "Barenkamp",
  "Bauerntanzstraße",
  "Baumblütenweg",
  "Bawinkeler Straße",
  "Bayernstraße",
  "Beckhookweg",
  "Beckstraße",
  "Beerenweg",
  "Beethovenstraße",
  "Bentheimer Straße",
  "Benzstraße",
  "Bergstraße",
  "Bernard-Grünberg-Straße",
  "Bernardstraße",
  "Bernd-Rosemeyer-Straße",
  "Bernh.-Lohmann-Straße",
  "Berthastraße",
  "Beversundern",
  "Biberweg",
  "Bienenweg",
  "Biener Straße",
  "Bienerfeldstraße",
  "Billrothstraße",
  "Binnenstraße",
  "Binsenweg",
  "Birkenallee",
  "Birkenstraße",
  "Birkhuhnstraße",
  "Bisamplatz",
  "Blaubeerenweg",
  "Blesshuhnweg",
  "Bonhoefferstraße",
  "Bookekkernweg",
  "Bookhofstraße",
  "Borgelweg",
  "Borkenweg",
  "Borkumer Straße",
  "Boschstraße",
  "Bottlage",
  "Brachvogelweg",
  "Brahmsweg",
  "Brambusch",
  "Bramharstraße",
  "Bramscher Straße",
  "Brauers Hof",
  "Braunschweiger Straße",
  "Brehmstraße",
  "Bremer Straße",
  "Breslauer Straße",
  "Brinkmannstraße",
  "Brockhausen",
  "Brockhauser Teiche",
  "Brockhauser Weg",
  "Brockortstraße",
  "Brombeerweg",
  "Brookstraße",
  "Bruchstraße",
  "Bruchwiesenweg",
  "Brucknerstraße",
  "Brunnenstraße",
  "Brögberhof",
  "Brögberner Straße",
  "Brömmelkampstraße",
  "Brümmers Weg",
  "Brümmers Wiese",
  "Buchenstraße",
  "Buchsbaumweg",
  "Burgstraße",
  "Burtenweg",
  "Buschweg",
  "Buskenweg",
  "Bussardweg",
  "Bärenwinkel",
  "Bäumerstraße",
  "Bögenstraße",
  "Böhmerhof",
  "Bülten",
  "Bürgermeister-Hinken-Straße",
  "Bürgermeister-Niemann-Straße",
  "Calvinstraße",
  "Carl-Zeiss-Straße",
  "Castellstraße",
  "Celler Straße",
  "Clara-Eylert-Straße",
  "Clemensstraße",
  "Cloppenburger Straße",
  "Clubstraße",
  "Clusorthstraße",
  "Colonatstraße",
  "Dahlers Kamp",
  "Dahlienweg",
  "Daimlerstraße",
  "Dalumer Straße",
  "Damaschkestraße",
  "Danckelmannsweg",
  "Dannappelweg",
  "Danziger Straße",
  "Darmer Esch",
  "Darmer Hafenstraße",
  "Darmer Kirchweg",
  "Deelengrund",
  "Deeringhook",
  "Deichstraße",
  "Delenweg",
  "Delpstraße",
  "Demannstraße",
  "Diekstraße",
  "Diepenbrockstraße",
  "Diepholzer Straße",
  "Dieselstraße",
  "Dietrichstraße",
  "Dillensand",
  "Distelgrund",
  "Dohlenweg",
  "Dollhoffstraße",
  "Donaustraße",
  "Dorfstraße",
  "Dr.-Lindgen-Straße",
  "Drei Berge",
  "Drohnenweg",
  "Drosselweg",
  "Duisenburger Straße",
  "Dusthook",
  "Dünenweg",
  "Dürerstraße",
  "Ebereschenweg",
  "Eckelkamp",
  "Edisonstraße",
  "Efeustraße",
  "Egbers Esch",
  "Eibenweg",
  "Eichenweg",
  "Eichhörnchenweg",
  "Eidechsenweg",
  "Eifelstraße",
  "Einsteinstraße",
  "Ekkelweg",
  "Elbestraße",
  "Elisabeth-Feldhaus-Straße",
  "Elisabethstraße",
  "Elkestraße",
  "Else-Cohen-Straße",
  "Elsenbusch",
  "Elsterstraße",
  "Emdener Straße",
  "Emmy-von-Dincklage-Straße",
  "Emsanger",
  "Emsauenallee",
  "Emsstraße",
  "Emsufer",
  "Erikaweg",
  "Erlenweg",
  "Eschstraße",
  "Espenweg",
  "Estringen",
  "Estringer Straße",
  "Fahrenheitstraße",
  "Falkenstraße",
  "Falterweg",
  "Farnweg",
  "Fasanenweg",
  "Feldhuhnweg",
  "Feldkamp",
  "Feldstraße",
  "Feuerdornstraße",
  "Fichtenweg",
  "Finkenweg",
  "Fischerstraße",
  "Fiskediek",
  "Flachsstraße",
  "Flachswischke",
  "Fledderbergstraße",
  "Fleerbeernweg",
  "Flemings Tannen",
  "Fliederweg",
  "Flinkersweg",
  "Flöttenwiske",
  "Flügelstraße",
  "Fokkestraße",
  "Forstweg",
  "Frankenstraße",
  "Frankfurter Straße",
  "Frerener Straße",
  "Friedensweg",
  "Friederikenstraße",
  "Friedhofsweg",
  "Friedlandstraße",
  "Friedr.-Ebert-Straße",
  "Friedrichstraße",
  "Friesenstraße",
  "Fröbelstraße",
  "Fuchsbau",
  "Fuchskuhlen",
  "Fuchsstraße",
  "Fuggerstraße",
  "Föhrenweg",
  "Gartenstraße",
  "Geersstraße",
  "Geester Straße",
  "Gelgöskenstiege",
  "Georgstraße",
  "Gerbertstraße",
  "Gerhard-Hilling-Straße",
  "Gerhard-Kues-Straße",
  "Gerhard-Rosken-Straße",
  "Gerhardstraße",
  "Geroldstraße",
  "Gerstenweg",
  "Geschw.-Scholl-Straße",
  "Gierenbergstraße",
  "Ginsterweg",
  "Glatzer Straße",
  "Gleesener Straße",
  "Glogauer Straße",
  "Goebelstraße",
  "Goerdelerstraße",
  "Goethestraße",
  "Goldschmidtstraße",
  "Gravelstraße",
  "Gregor-Dall-Straße",
  "Gregor-Mendel-Weg",
  "Greiwehof",
  "Grenzweg",
  "Grillenweg",
  "Große Straße",
  "Große-Honebrink-Straße",
  "Großer Sand",
  "Grüner Weg",
  "Grünewaldstraße",
  "Gutenbergweg",
  "Gymnasialstraße",
  "Gärtnereistraße",
  "Göttinger Straße",
  "Günneweg",
  "Haarweg",
  "Habichtweg",
  "Haflingerstraße",
  "Hagebuttenweg",
  "Hagengarten",
  "Hagenstraße",
  "Hahnemannstraße",
  "Hainbuchenweg",
  "Hanauerweg",
  "Handelsstraße",
  "Hanfstraße",
  "Hanna-Mecke-Weg",
  "Hannoveranerstraße",
  "Harzstraße",
  "Haselnussweg",
  "Haselünner Straße",
  "Haydnstraße",
  "Heckenrosenweg",
  "Hedonallee",
  "Heidekampstraße",
  "Heidekrautweg",
  "Heidelbeerenweg",
  "Heidestraße",
  "Heikestraße",
  "Heinrich-Kohl-Straße",
  "Heinrich-Middendorf-Straße",
  "Heinrich-Schniers-Straße",
  "Heinrich-Voß-Straße",
  "Heinrich-Weltring-Straße",
  "Heinrichstraße",
  "Helgolandstraße",
  "Hellweg",
  "Hensenmühle",
  "Hermann-Gilles-Platz",
  "Hermann-Heuking-Straße",
  "Hermann-Koke-Straße",
  "Hermann-Löns-Straße",
  "Hermannstraße",
  "Hermelinweg",
  "Herrenkamp",
  "Herzford",
  "Herzforder Straße",
  "Hessenweg",
  "Heuberge",
  "Heuesch",
  "Heugrabenstraße",
  "Heuwüste",
  "Hexenkamp",
  "Hildesheimer Straße",
  "Himbeerenweg",
  "Hirschberger Straße",
  "Hirschgraben",
  "Hoepnerstraße",
  "Hohenberger Weide",
  "Hohenfeldstraße",
  "Hohenpfortenweg",
  "Hohlweg",
  "Holbeinstraße",
  "Holstenstraße",
  "Holterhueshof",
  "Holthaarstraße",
  "Holthauser Esch",
  "Holthauser Straße",
  "Holunderweg",
  "Holzkamp",
  "Honigweg",
  "Honlenwehrstraße",
  "Hoogenhook",
  "Horkelstraße",
  "Horstweg",
  "Hubertusstraße",
  "Hufelandstraße",
  "Hummelweg",
  "Hunsrückstraße",
  "Husarenstraße",
  "Häherweg",
  "Händelweg",
  "Hörmeyers Hof",
  "Hövelweg",
  "Hügelweg",
  "Hülsekrabbenweg",
  "Hüsinger Hook",
  "Hüveder Straße",
  "Igelweg",
  "Ilexweg",
  "Iltisplatz",
  "Im Brooke",
  "Im Eck",
  "Im Eichenbusch",
  "Im Erlengrund",
  "Im Fenn",
  "Im Gauer",
  "Im Grunde",
  "Im Heidegrund",
  "Im Holz",
  "Im Kamp-Hoog",
  "Im Keil",
  "Im Lägermarsch",
  "Im Rehwinkel",
  "Im Sanfelde",
  "Im Schibbel",
  "Im Timpen",
  "Im Winkel",
  "Im Wäldchen",
  "Immenhook",
  "Immenweg",
  "In den Hornen",
  "In den Sandbergen",
  "In den Strubben",
  "In der Bauerschaft",
  "In der Dickung",
  "In der Heide",
  "Jagdweg",
  "Jahnstraße",
  "Jakob-Wolff-Platz",
  "Jakob-Wolff-Straße",
  "Jansenweg",
  "Jasminstraße",
  "Jochem-Hamann-Straße",
  "Johann-Strauß-Straße",
  "Johannes-Meyer-Straße",
  "Johannesstraße",
  "Johanniskrautweg",
  "Josef-Kaiser-Straße",
  "Josef-Terstiege-Straße",
  "Josef-Wolke-Straße",
  "Josefstraße",
  "Joseph-Schwegmann-Straße",
  "Juister Straße",
  "Julius-Landzettel-Straße",
  "Julius-Leber-Straße",
  "Jupiterstraße",
  "Jägerplatz",
  "Jägerstraße",
  "Kaiserstraße",
  "Kalmers Kamp",
  "Kampstraße",
  "Kanalgasse",
  "Kapellenweg",
  "Kardinal-von-Galen-Straße",
  "Karlstraße",
  "Karolinenstraße",
  "Kastanienweg",
  "Katharinenstraße",
  "Keplerstraße",
  "Kerkströttken",
  "Keselingstraße",
  "Kettelerstraße",
  "Kiebitzweg",
  "Kiefernstraße",
  "Kiesbahn",
  "Kiesbergstraße",
  "Kieselweg",
  "Kirchenkamp",
  "Kirchstraße",
  "Kirchwand",
  "Kitzweg",
  "Kivelingstraße",
  "Klasingstraße",
  "Kleekamp",
  "Kleinbahnweg",
  "Knickweg",
  "Kohlrauschstraße",
  "Kohschultenkamp",
  "Kohspiek",
  "Kolberger Straße",
  "Kolkstraße",
  "Kollwitzstraße",
  "Kolpingstraße",
  "Koninger Esch",
  "Konrad-Adenauer-Ring",
  "Koopmanns Kamp",
  "Koorskamp",
  "Kopernikusstraße",
  "Koppelweg",
  "Kornblumenweg",
  "Kornweg",
  "Kriegerstraße",
  "Kringstraße",
  "Krokusweg",
  "Kropps Garten",
  "Kroppstraße",
  "Krummacher Weg",
  "Krusestraße",
  "Krögers Kamp",
  "Kuckuckstraße",
  "Kuhlhof",
  "Kurze Straße",
  "Käferweg",
  "Königsberger Straße",
  "Kösterhook",
  "Kötterhook",
  "Lambersteipenweg",
  "Lampenkamp",
  "Landrienstraße",
  "Lange Straße",
  "Langenbielauer Straße",
  "Langener Straße",
  "Langer Esch",
  "Langschmidtsweg",
  "Lavendelweg",
  "Laxtener Brook",
  "Laxtener Straße",
  "Leharweg",
  "Lengericher Straße",
  "Lenzfeld",
  "Lenzstraße",
  "Lerchenstraße",
  "Libellenweg",
  "Liebfrauenkamp",
  "Liegnitzer Weg",
  "Ligusterweg",
  "Lilienweg",
  "Lindeneck",
  "Lindenstraße",
  "Lingerfeldstraße",
  "Lohner Straße",
  "Lookenstraße",
  "Loosstraße",
  "Loowstraße",
  "Loppenmoor",
  "Lortzingstraße",
  "Louis-Goosmann-Straße",
  "Louis-Mendelssohn-Straße",
  "Lucaskamp",
  "Luchswinkel",
  "Ludgeristraße",
  "Ludwigstraße",
  "Luisenstraße",
  "Lögerings Esch",
  "Löninger Straße",
  "Löpkers Kamp",
  "Löwenzahnweg",
  "Lükenfeld",
  "Lüneburger Straße",
  "Lütkefeldstraße",
  "Maiknechtstraße",
  "Mainstraße",
  "Marderplatz",
  "Margarethe-Heinze-Straße",
  "Margeritenweg",
  "Maria-Mönch-Tegeder-Straße",
  "Marie-Curie-Straße",
  "Marienstraße",
  "Marthastraße",
  "Martin-Luther-Straße",
  "Martinstraße",
  "Masebergstraße",
  "Mathilde-Vaerting-Straße",
  "Max-Planck-Weg",
  "Maximilian-Kolbe-Straße",
  "Meilingstraße",
  "Meisenstraße",
  "Mengers Weg",
  "Menzelstraße",
  "Meppener Straße",
  "Meschweg",
  "Mindener Straße",
  "Miquelstraße",
  "Mitteldorfweg",
  "Mittelstraße",
  "Mohnstraße",
  "Mohrmannstraße",
  "Molkereistraße",
  "Montessoristraße",
  "Moosvenner Weg",
  "Moosweg",
  "Moselstraße",
  "Mozartstraße",
  "Moßfeld",
  "Mundersumer Straße",
  "Möddelhof",
  "Möllenweg",
  "Möllerweg",
  "Mühlenbachstraße",
  "Mühlengraben",
  "Mühlenstiege",
  "Mühlentorstraße",
  "Mühlenweg",
  "Müllers Kamp",
  "Münnigbürener Weg",
  "Münsteraner Straße",
  "Nachtigallenstraße",
  "Nadelweg",
  "Nansenstraße",
  "Narzissenweg",
  "Nelkenweg",
  "Neubrockhausen",
  "Neue Siedlung",
  "Neue Straße",
  "Neuer Wall",
  "Neuholthausener Straße",
  "Niebuers Kamp",
  "Niederdarmer Straße",
  "Niedersachsenstraße",
  "Niels-Stensen-Straße",
  "Nikolaus-Groß-Straße",
  "Noltestraße",
  "Nordhorner Straße",
  "Nordlohner Straße",
  "Nordstraße",
  "Nussbaumweg",
  "Nöldekestraße",
  "Oberhofstraße",
  "Odenwaldstraße",
  "Offenbachstraße",
  "Oldenburger Straße",
  "Oldenweg",
  "Olgastraße",
  "Olympiaweg",
  "Osnabrücker Straße",
  "Osterbergstraße",
  "Osterkampstraße",
  "Otterplatz",
  "Otto-Hahn-Straße",
  "Otto-Lilienthal-Straße",
  "Otto-von-Guericke-Ring",
  "Ottostraße",
  "Overbergstraße",
  "Papenburger Straße",
  "Pappelweg",
  "Parkstraße",
  "Passgang",
  "Pastor-Dunkmann-Straße",
  "Paulstraße",
  "Pestalozzistraße",
  "Pfarrtannen",
  "Pferdeweg",
  "Pfälzer Straße",
  "Pirschweg",
  "Plankorther Straße",
  "Poggenborg",
  "Poggenmeer",
  "Polle",
  "Poller Sand",
  "Poller Straße",
  "Pommernstraße",
  "Pontanusstraße",
  "Poststraße",
  "Potcampstraße",
  "Prozessionsweg",
  "Pölkerskamp",
  "Pöttkerdiek",
  "Quellenweg",
  "Querweg",
  "Rabergweg",
  "Radberg",
  "Raffineriestraße",
  "Raiffeisenstraße",
  "Ramsel Dorf",
  "Ramseler Straße",
  "Rathausgasse",
  "Rauhe Venne",
  "Raydtstraße",
  "Rebhuhnweg",
  "Rehtränke",
  "Reichenbacher Straße",
  "Reiherhorst",
  "Reisigweg",
  "Reiterweg",
  "Rembrandtstraße",
  "Rensing Kamp",
  "Resedaweg",
  "Reuterstraße",
  "Rheiner Straße",
  "Rheitlager Weg",
  "Richard-Hermeling-Straße",
  "Richard-Uhle-Straße",
  "Rietmeyerstraße",
  "Rietstraße",
  "Ringstraße",
  "Robert-Koch-Straße",
  "Roggenweg",
  "Rohrweg",
  "Rohstraße",
  "Rolandstraße",
  "Rolingshof",
  "Rommelstraße",
  "Rosengartenstraße",
  "Rosenstraße",
  "Rotbuchenweg",
  "Rothertstraße",
  "Rottumer Straße",
  "Rubensstraße",
  "Ruth-Foster-Straße",
  "Ruth-West-Platz",
  "Röntgenstraße",
  "Rühmberg",
  "Rüskenweg",
  "Sachsenstraße",
  "Salzstraße",
  "Sandberg",
  "Sandbrinkerheidestraße",
  "Sandesch",
  "Sandhasenstraße",
  "Sandpoolstraße",
  "Sandstraße-Nord",
  "Sandstraße-Süd",
  "Sandwand",
  "Saturnring",
  "Sauerbruchstraße",
  "Sauerlandstraße",
  "Schallenbruch",
  "Scharnhorststraße",
  "Schießstandstraße",
  "Schilfweg",
  "Schillerstraße",
  "Schlachterstraße",
  "Schleheneck",
  "Schmetterlingsweg",
  "Schmiedestraße",
  "Schnittkamp",
  "Schoolweg",
  "Schottelhof",
  "Schulkampstraße",
  "Schulstraße",
  "Schumannstraße",
  "Schwabenstraße",
  "Schwalbenweg",
  "Schwarzer Weg",
  "Schwedenschanze",
  "Schwennestraße",
  "Schöttmers Wiese",
  "Schückingstraße",
  "Schülerpfad",
  "Schüttelsand",
  "Schüttorfer Straße",
  "Schützenhügel",
  "Schützenstraße",
  "Sebastianstraße",
  "Seerosenweg",
  "Seggenweg",
  "Seidelbastweg",
  "Semmelweisstraße",
  "Silbergrasweg",
  "Silvesterplatz",
  "Sollingstraße",
  "Sommeringen",
  "Sommeringer Straße",
  "Sonnenblumenweg",
  "Sonnenhügel",
  "Sonnentauweg",
  "Sonnenweg",
  "Sophienstraße",
  "Spechtweg",
  "Sperberweg",
  "Spessartstraße",
  "Spiekerooger Straße",
  "Spycksweg",
  "Stader Straße",
  "Staggenburg",
  "Stahljans Hof",
  "Starenweg",
  "Stationsweg",
  "Stephanstraße",
  "Sternstraße",
  "Stettiner Straße",
  "Stieglitzweg",
  "Stodtbrochstraße",
  "Storchenweg",
  "Stormstraße",
  "Strauchweg",
  "Strodts Esch",
  "Strootstraße",
  "Struckstraße",
  "Sturmstraße",
  "Suurhookstraße",
  "Sylter Straße",
  "Synagogenstraße",
  "Sändkerstraße",
  "Südeschstraße",
  "Tannenkamp",
  "Tannenweg",
  "Taubenweg",
  "Taunusstraße",
  "Tecklenburger Straße",
  "Teichstraße",
  "Tewesweg",
  "Theresia-Brüning-Straße",
  "Thiens Heide",
  "Thuiner Straße",
  "Thüringer Straße",
  "Tiefer Weg",
  "Timmers Wiese",
  "Trabweg",
  "Trakehnerstraße",
  "Traubenkirschweg",
  "Trensenweg",
  "Tulpenweg",
  "Turmstraße",
  "Turnweg",
  "Töltstraße",
  "Uhlenweg",
  "Uhuweg",
  "Ulanenstraße",
  "Ulmenweg",
  "Universitätsplatz",
  "Unter den Eichen",
  "Van-Acken-Straße",
  "Veddernberg",
  "Veilchenweg",
  "Vennestraße",
  "Vennwiske",
  "Verdener Weg",
  "Virchowstraße",
  "Vogelbeernweg",
  "Vogelsang",
  "Vogtstraße",
  "Von-Behring-Straße",
  "Von-Bergmann-Straße",
  "Von-Droste-Hülshoff-Straße",
  "Von-Eichendorff-Straße",
  "Von-Humboldt-Weg",
  "Von-Liebig-Weg",
  "Von-Pettenkofer-Straße",
  "Von-Quadt-Straße",
  "Von-Reusch-Straße",
  "Von-Stauffenberg-Straße",
  "Von-Stülpnagel-Straße",
  "Von-Suttner-Straße",
  "Von-Tresckow-Straße",
  "Von-Zeppelin-Straße",
  "Vorderwälde",
  "Wachendorfer Straße",
  "Wacholderstraße",
  "Wachtelweg",
  "Wagnerstraße",
  "Waldstraße",
  "Wallheckenstraße",
  "Wallkamp",
  "Wangerooger Straße",
  "Weidelgrasweg",
  "Weidenkamp",
  "Weidestraße",
  "Weinmannstraße",
  "Weissdornweg",
  "Weizenweg",
  "Wellbergstraße",
  "Werkstättenstraße",
  "Werndlystraße",
  "Werner-von-Beesten-Straße",
  "Werner-von-Siemens-Straße",
  "Wesel",
  "Weseler Straße",
  "Weserstraße",
  "Wespenweg",
  "Westenesch",
  "Westfalenstraße",
  "Wichernstraße",
  "Wieselplatz",
  "Wiesenstraße",
  "Wietmarscher Straße",
  "Wildpfad",
  "Wilhelm-Berning-Straße",
  "Wilhelm-Maybach-Straße",
  "Wilhelmstraße",
  "Willy-Brandt-Ring (gerade Hausnummern)",
  "Willy-Brandt-Ring (ungerade Hausnummern)",
  "Windmühlenberg",
  "Windthorststraße",
  "Wittenbergring",
  "Wittenbruch",
  "Wolfsburger Straße",
  "Wolfseck",
  "Wolkenkamp",
  "Wollgrasweg",
  "Zedernweg",
  "Zeisigweg",
  "Zu den Buchen",
  "Zum Biener Busch",
  "Zum Birkenhof",
  "Zum Bruch",
  "Zum Dorfplatz",
  "Zum Eichenhof",
  "Zum Eichenkamp",
  "Zum Emsstrand",
  "Zum Emswehr",
  "Zum Feuerwehrhaus",
  "Zum Glockenturm",
  "Zum Gut Herzford",
  "Zum Hagen",
  "Zum Heidhof",
  "Zum Heuland",
  "Zum Holtkamp",
  "Zum Kanalufer",
  "Zum Lau",
  "Zum Neuen Hafen",
  "Zum Niederfeld",
  "Zum Pumpenhaus",
  "Zum Rehstand",
  "Zur Baccumer Mühle",
  "Zur Becke",
  "Zur Burte",
  "Zur Dille",
  "Zur Drehangel",
  "Zur Kalmer",
  "Zur Kiesgrube",
  "Zur Laake",
  "Zur Mili",
  "Zur Rethlage",
  "Zur Schöttmer",
  "Zwischen den Brücken",
  "Zwischenweg",
  "Östliche Stadtflur"
];